package io.github.longislandicetea.dshnative

import kotlinx.serialization.json.JsonObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * A background job arrives as a `user/message` whose `source.kind` is `plugin`.
 *
 * Two bugs these tests pin down. Rendering such a message as chat text made the
 * harness look like the person typing, so job output landed in the transcript as
 * if the user had pasted it. And the first attempt at a title read only
 * `source.summary`, which `model-selection` and `user-approval` do not send, so
 * those notices silently fell back to a generic label.
 *
 * The bodies below are copied from real `session.v3.jsonl` records rather than
 * invented, because the shape of `source` is what the code depends on.
 */
class NoticeCardTest {
    private fun event(json: String): SessionEvent {
        val data = DshWire.json.parseToJsonElement(json)
        return SessionEvent(seq = 1, type = "user/message", time = 0, data = data)
    }

    /** A finished background job, as `tool-jobs` writes it. */
    private val toolsJob = event(
        """
        {"content":[{"type":"text","text":"background job bash-2 (bash: /tmp/setup.sh) finished [status: completed, exit code: 127]"}],
         "source":{"kind":"plugin","plugin":"tool-jobs","form":"notice",
         "summary":"bash /tmp/setup.sh > /tmp/setup.log 2>&1 [status: completed, exit code: 127]"}}
        """.trimIndent(),
    )

    /** A model switch notice: plugin-sourced, `form: notice`, but no summary. */
    private val modelSwitch = event(
        """
        {"content":[{"type":"text","text":"[model changed: assistant turns above this point were generated by a; the session continues with b]"}],
         "source":{"kind":"plugin","plugin":"model-selection","form":"notice","summary":"a/b → c/d"}}
        """.trimIndent(),
    )

    private val approvalPolicy = event(
        """
        {"content":[{"type":"text","text":"The approval policy changed from \"never\" to \"ask\" (changed by the user)."}],
         "source":{"kind":"plugin","plugin":"user-approval","form":"notice"}}
        """.trimIndent(),
    )

    /** A real user message must never be mistaken for a notice. */
    private val human = event(
        """{"content":[{"type":"text","text":"hello"}],"source":{"kind":"user"}}""",
    )

    @Test
    fun `a background job is recognised as a plugin notice`() {
        assertEquals("tool-jobs", EventPayload.noticePlugin(toolsJob))
        assertEquals(true, EventPayload.isNotice(toolsJob))
    }

    @Test
    fun `the summary becomes the collapsed line`() {
        assertEquals(
            "bash /tmp/setup.sh > /tmp/setup.log 2>&1 [status: completed, exit code: 127]",
            EventPayload.noticeSummary(toolsJob),
        )
    }

    @Test
    fun `a notice without a summary still names its plugin`() {
        assertEquals("user-approval", EventPayload.noticePlugin(approvalPolicy))
        assertNull(EventPayload.noticeSummary(approvalPolicy))
    }

    @Test
    fun `a model switch keeps the plugin as its title`() {
        assertEquals("model-selection", EventPayload.noticePlugin(modelSwitch))
        assertEquals("a/b → c/d", EventPayload.noticeSummary(modelSwitch))
    }

    @Test
    fun `a human message is not a notice`() {
        assertNull(EventPayload.noticePlugin(human))
        assertEquals(false, EventPayload.isNotice(human))
    }

    @Test
    fun `only the first summary line is used`() {
        val multi = event(
            """
            {"content":[{"type":"text","text":"..."}],
             "source":{"kind":"plugin","plugin":"tool-jobs","form":"notice","summary":"first line\nsecond line"}}
            """.trimIndent(),
        )
        assertEquals("first line", EventPayload.noticeSummary(multi))
    }

    /** `system/message` also carries a plugin source but is never a user-facing card. */
    @Test
    fun `a system message is not treated as a plugin notice`() {
        val data = DshWire.json.parseToJsonElement(
            """{"turn":1,"step":1,"message":{"role":"system",
               "content":[{"type":"text","text":"prompt"}],
               "source":{"kind":"plugin","plugin":"@deepseek-ai/dsh-system-prompt"}}}""",
        )
        val system = SessionEvent(seq = 1, type = "system/message", time = 0, data = data)
        // The plugin is reported from `data.message.source`, which the payload
        // accessors do not look at, so a system prompt cannot surface as a card.
        assertNull(EventPayload.noticePlugin(system))
    }

    @Test
    fun `data without a source object is not a notice`() {
        val bare = event("""{"content":[{"type":"text","text":"hi"}]}""")
        assertNull(EventPayload.noticePlugin(bare))
        assertNull(EventPayload.noticeSummary(bare))
        assertEquals(false, EventPayload.isNotice(bare))
    }
}
