package io.github.longislandicetea.dshnative

import kotlinx.serialization.json.JsonObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * A background job arrives as a `user/message` whose `source.kind` is `plugin`.
 *
 * Two bugs these tests pin down. Rendering such a message as chat text made the
 * harness look like the person typing, so job output landed in the transcript as
 * if the user had pasted it. And the first attempt at a title read only
 * `source.summary`, which `model-selection` and `user-approval` do not send, so
 * those notices silently fell back to a generic label.
 *
 * The bodies below are copied from real `session.v3.jsonl` records rather than
 * invented, because the shape of `source` is what the code depends on.
 */
class NoticeCardTest {
    private fun event(json: String): SessionEvent {
        val data = DshWire.json.parseToJsonElement(json)
        return SessionEvent(seq = 1, type = "user/message", time = 0, data = data)
    }

    /** A finished background job, as `tool-jobs` writes it. */
    private val toolsJob = event(
        """
        {"content":[{"type":"text","text":"background job bash-2 (bash: /tmp/setup.sh) finished [status: completed, exit code: 127]"}],
         "source":{"kind":"plugin","plugin":"tool-jobs","form":"notice",
         "summary":"bash /tmp/setup.sh > /tmp/setup.log 2>&1 [status: completed, exit code: 127]"}}
        """.trimIndent(),
    )

    /** A model switch notice: plugin-sourced, `form: notice`, but no summary. */
    private val modelSwitch = event(
        """
        {"content":[{"type":"text","text":"[model changed: assistant turns above this point were generated by a; the session continues with b]"}],
         "source":{"kind":"plugin","plugin":"model-selection","form":"notice","summary":"a/b → c/d"}}
        """.trimIndent(),
    )

    private val approvalPolicy = event(
        """
        {"content":[{"type":"text","text":"The approval policy changed from \"never\" to \"ask\" (changed by the user)."}],
         "source":{"kind":"plugin","plugin":"user-approval","form":"notice"}}
        """.trimIndent(),
    )

    /** A real user message must never be mistaken for a notice. */
    private val human = event(
        """{"content":[{"type":"text","text":"hello"}],"source":{"kind":"user"}}""",
    )

    /**
     * A relayed subagent message.
     *
     * The bug this exists for: detection tested `source.kind == "plugin"`, so a
     * relay (`agent-message`) fell through to the human bubble and a subagent's
     * report appeared as if the user had typed it.
     */
    private val relayed = event(
        """{"content":[{"type":"text","text":"Agent aaaa1111-2222-3333-4444-555566667777 sent a message:"},
           {"type":"text","text":"DONE — figure rebuilt."}],
           "source":{"kind":"agent-message","form":"relay","senderSessionId":"aaaa1111-2222-3333-4444-555566667777"}}""",
    )

    /** A subagent finishing, which carries a summary and its sender. */
    private val settled = event(
        """{"content":[{"type":"text","text":"Background subagent aaaa1111 finished and will do no further work."},
           {"type":"text","text":"Its closing message:"},{"type":"reasoning","text":"thinking"}],
           "source":{"kind":"subagent-settled","form":"notice",
           "summary":"Background subagent aaaa1111 failed before it finished.",
           "senderSessionId":"aaaa1111-2222-3333-4444-555566667777"}}""",
    )

    /** Harness-injected inputs: long, repetitive, and not conversation. */
    private val instructions = event(
        """{"content":[{"type":"text","text":"<system-reminder> Additional instructions from: AGENTS.md"}],
           "source":{"kind":"agent-instructions","form":"instructions"}}""",
    )

    private val skillCatalog = event(
        """{"content":[{"type":"text","text":"<system-reminder> A skill is a reusable set of task-specific instructions"}],
           "source":{"kind":"skill-catalog","form":"catalog","entries":[]}}""",
    )

    @Test
    fun `a background job is recognised as a plugin notice`() {
        assertEquals("tool-jobs", EventPayload.noticePlugin(toolsJob))
        assertEquals(true, EventPayload.isNotice(toolsJob))
    }

    @Test
    fun `the summary becomes the collapsed line`() {
        assertEquals(
            "bash /tmp/setup.sh > /tmp/setup.log 2>&1 [status: completed, exit code: 127]",
            EventPayload.noticeSummary(toolsJob),
        )
    }

    @Test
    fun `a notice without a summary still names its plugin`() {
        assertEquals("user-approval", EventPayload.noticePlugin(approvalPolicy))
        assertNull(EventPayload.noticeSummary(approvalPolicy))
    }

    @Test
    fun `a model switch keeps the plugin as its title`() {
        assertEquals("model-selection", EventPayload.noticePlugin(modelSwitch))
        assertEquals("a/b → c/d", EventPayload.noticeSummary(modelSwitch))
    }

    @Test
    fun `a human message is not a notice`() {
        assertNull(EventPayload.noticePlugin(human))
        assertEquals(false, EventPayload.isNotice(human))
        assertEquals("user", EventPayload.sourceKind(human))
    }

    @Test
    fun `a relayed subagent message is a notice, not a user message`() {
        assertEquals("agent-message", EventPayload.sourceKind(relayed))
        assertEquals(true, EventPayload.isNotice(relayed))
        assertEquals(false, EventPayload.isHiddenSource(relayed))
        // No plugin name: the card falls back to the kind, and the sender is what
        // says which subagent spoke.
        assertNull(EventPayload.noticePlugin(relayed))
        assertEquals("aaaa1111-2222-3333-4444-555566667777", EventPayload.senderSessionId(relayed))
    }

    @Test
    fun `a settled subagent is a notice with a summary and a sender`() {
        assertEquals("subagent-settled", EventPayload.sourceKind(settled))
        assertEquals(true, EventPayload.isNotice(settled))
        assertEquals(false, EventPayload.isHiddenSource(settled))
        assertEquals(
            "Background subagent aaaa1111 failed before it finished.",
            EventPayload.noticeSummary(settled),
        )
        assertEquals("aaaa1111-2222-3333-4444-555566667777", EventPayload.senderSessionId(settled))
    }

    @Test
    fun `injected instructions and the skill catalog are hidden`() {
        // These repeat on every change and are inputs to the harness, not turns of
        // the conversation; before the fix they rendered as user bubbles.
        for (injected in listOf(instructions, skillCatalog)) {
            assertEquals(true, EventPayload.isHiddenSource(injected))
        }
        assertEquals(false, EventPayload.isHiddenSource(relayed))
        assertEquals(false, EventPayload.isHiddenSource(human))
    }

    @Test
    fun `every non-user source is machinery`() {
        // The rule itself, stated once: only `kind == "user"` is a person.
        val kinds = listOf("plugin", "agent-message", "subagent-settled", "agent-instructions", "skill-catalog")
        for (kind in kinds) {
            val e = event("""{"content":[{"type":"text","text":"x"}],"source":{"kind":"$kind"}}""")
            assertEquals("$kind must be machinery", true, EventPayload.isNotice(e))
        }
    }

    @Test
    fun `a message with no source kind keeps its old behaviour`() {
        // Absent kind: a fallback target with no source is not a notice, and the
        // classifier must not crash on it.
        val noSource = event("""{"content":[{"type":"text","text":"hi"}]}""")
        assertNull(EventPayload.sourceKind(noSource))
        assertEquals(false, EventPayload.isNotice(noSource))
        assertEquals(false, EventPayload.isHiddenSource(noSource))
    }

    @Test
    fun `only the first summary line is used`() {
        val multi = event(
            """
            {"content":[{"type":"text","text":"..."}],
             "source":{"kind":"plugin","plugin":"tool-jobs","form":"notice","summary":"first line\nsecond line"}}
            """.trimIndent(),
        )
        assertEquals("first line", EventPayload.noticeSummary(multi))
    }

    /** `system/message` also carries a plugin source but is never a user-facing card. */
    @Test
    fun `a system message is not treated as a plugin notice`() {
        val data = DshWire.json.parseToJsonElement(
            """{"turn":1,"step":1,"message":{"role":"system",
               "content":[{"type":"text","text":"prompt"}],
               "source":{"kind":"plugin","plugin":"@deepseek-ai/dsh-system-prompt"}}}""",
        )
        val system = SessionEvent(seq = 1, type = "system/message", time = 0, data = data)
        // The plugin is reported from `data.message.source`, which the payload
        // accessors do not look at, so a system prompt cannot surface as a card.
        assertNull(EventPayload.noticePlugin(system))
    }

    @Test
    fun `data without a source object is not a notice`() {
        val bare = event("""{"content":[{"type":"text","text":"hi"}]}""")
        assertNull(EventPayload.noticePlugin(bare))
        assertNull(EventPayload.noticeSummary(bare))
        assertEquals(false, EventPayload.isNotice(bare))
    }
}
